version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: key for orders
            tests : 
            - not_null 

          - name: products_id
            description: products reference / sku 
            tests:
              - not_null

          - name: qty

          - name: turnover
            description: final turnover with promos 
            tests:
              - not_null

          - name: purchase_cost
            description: unit cost for each product 
            tests:
              - not_null

          - name: margin